//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

const (
	sourceDir = "../../tmp/frontend"
	outputFile = "assets_gen.go"
)

func main() {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by assets.go; DO NOT EDIT.\n")
	buffer.WriteString("package main\n\n")
	buffer.WriteString("var embeddedFiles = map[string]string{\n")

	err := filepath.WalkDir(sourceDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		relPath, err := filepath.Rel(sourceDir, path)
		if err != nil {
			return err
		}

		if err != nil {
			return err
		}

		contentBytes, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		content := base64.RawStdEncoding.EncodeToString(contentBytes)

		buffer.WriteString(fmt.Sprintf("\t\"/%s\": `%s`,\n", relPath, content))

		return nil
	})
	
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking the path: %v\n", err)
		os.Exit(1)
	}

	buffer.WriteString("}\n")

	err = os.WriteFile(outputFile, buffer.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing generated file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated", outputFile)
}
